# Generated by Django 5.1.3 on 2024-11-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username',), name='unique_username'), models.UniqueConstraint(fields=('email',), name='unique_email')],
            },
        ),
    ]
